config/routes.rb
Rails.application.routes.draw do

  get '/' => 'tickets#index'

  get '/tickets' => 'tickets#tickets'
  get '/tickets/soldout' => 'tickets#soldout'
  post '/tickets/submit' => 'tickets#submit'

  get '/sponsors' => 'sponsors#sponsors'
  post '/sponsors/submit' => 'sponsors#submit'

  get '/admin' => 'admins#show'


  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/team' => 'tickets#team'


  get '/sponsors/logo' => 'sponsors#sponsor_logo'


end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  def my_save(token)
    Stripe.api_key = "sk_test_OgmM5tL6FSzS7ULyDFIuUYbn"
    # Create the charge on stripe's servers - this will charge the user's card
    begin
      charge = Stripe::Charge.create(
        :amount => 20000, # amount in cents
        :currency => "aud",
        :source => token,
        :description => "Ticket purchase"
      )
    rescue Stripe::CardError => e
      # The card has been declined
    end
    self.save
  end
end

app/controllers/tickets_controller.rb
require 'stripe'
require 'pony'

class TicketsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @sponsors = Sponsor.order("#{sort_column} #{sort_direction}")
    @speakers = Speaker.all

    ticket_price = 200
    total_num_of_tix = 200
    total_sponsor_amount = Sponsor.total_sponsorship

    ticket_discount = (total_sponsor_amount / total_num_of_tix)
    progress_deci = (ticket_discount.to_f / ticket_price)

    @progress = (progress_deci)
    @current_price = ticket_price.to_f - ticket_discount.to_f

  end

  def submit
    # generates random number and removes the part before decimal
    reference_id = rand(1.5..2.8).to_s.split(".")[1]
    new_ticket = Ticket.new
    new_ticket.first_name = params[:firstname]
    new_ticket.last_name = params[:lastname]
    new_ticket.email = params[:email]
    new_ticket.ref_id = reference_id
    new_ticket.num_of_tickets = params[:num_of_tickets]
    # create charge in ticket model
    new_ticket.my_save(params[:stripeToken])
    # get response from strip API.
    flash[:notice] = "Thanks for buying ticket/s to WDI Conf! Please check your email for confirmation. We look forward to seeing you there. (Click to close)"
    # sending conformation email
    Pony.mail({
  	:from => 'isha.negi19@gmail.com',
    :to => "#{params[:email]}",
    :subject => "Ticket Confirmation from WDI Conf 2016",
    :body => "Dear #{params[:firstname]}, Thanks for purchasing ticket/s to WDI Conf. Your reference number is #{reference_id}. We look forward to seeing you on May 27 2016 at General Assembly, Level 12A, 45 William Street, Melbourne! Kind regards, WDI Conf Organisers.",
    :via => :smtp,
    :via_options => {
      :address              => 'smtp.gmail.com',
      :port                 => '587',
      :enable_starttls_auto => true,
      :user_name            => 'johnmann778@gmail.com',
      :password             => 'password18*',
      :authentication       => :plain,
      :domain               => "localhost.localdomain"
     }
    })
    redirect_to '/'
  end

  private
    def sortable_columns
      [ "amount"]
    end

    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : "amount"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

end

app/views/tickets/_events.html.erb
<div class="events-container">
  <div class="container">
    <hr id="four" data-symbol="EVENTS">
    <div class="row row-event">
      <div class="one-half column">
        <h3>Doughnuts at dawn</h3>
        <h4>Friday 27th May, 7.30AM</h4>
        <p>
          Before settling in for two days of conference action, <span class="bolded">Envato</span> would like to treat all attendees to a breakfast feast. Our keynote speakers will probably be hanging by the doughnuts table if you want to chat, otherwise you'll be able to meet the other conference go-ers.
        </p><br>
        <p class="bolded">
          From 7:30AM at General Assembly
        </p>
      </div>

      <div class="one-half column">
        <img class="event-photo" id="event-one" src="" alt="" />
      </div>
    </div>


      <div class="row row-event">
        <div class="one-half column">
          <img class="event-photo" id="event-two" src="" alt="" />
        </div>

        <div class="one-half column">
          <h3>Keynote: Contributing to open source as a junior</h3>
          <h4>Friday 27 May, 9AM</h4>
          <p>
            For those starting out in the software development world, contributing to open source projects can feel pretty out of reach and intimidating. Your inner monologue might sound something like, 'what if people laugh at my PR's?' or 'how do I even start to understand such a large codebase?'. Pranati will be addressing some fundamental questions on how the open source world works, and how you can actually enhance your learning journey by reading and contributing to open source projects.
          </p><br>
          <p class="bolded">
            Starts 9AM sharp in the Main Event Space
          </p>
        </div>
      </div>

      <div class="row row-event">
        <div class="one-half column">
          <h3>You code like a girl. Good for you!</h3>
          <h4>Friday 27 May, 10AM</h4>
          <p>
            Christie discusses the benefits of diversity in teams. It has been scientifically proven that teams made up of members from diverse backgrounds outperform teams of a more homogenous demographic, and Christie explores this topic with experience running her own teams. You will learn how you can attract a diverse team, and how creating a culture of inclusiveness and understanding will get amazing results for your business.
          </p>
        </div>

        <div class="one-half column">
          <img class="event-photo" id="event-three" src="" alt="" />
        </div>
      </div>

  </div>

</div>

app/views/tickets/_hero.html.erb
<!-- Payment Confirmation  -->
<div class="notice">
    <% if flash[:notice] %>
    <%= flash[:notice] %>
    <% end %>
</div>

<!-- END Payment Confirmation  -->

<div class="hero-background">
<!-- stars   -->
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<div class="star"></div>
<!-- end of stars -->
  <div class="hero-container">
      <div class="">
          <!-- chart code -->
          <span id="progress" style="display:none"><%= @progress %></span>
            <div class="chart-wrapper">
              <div id="progresschart">
                <div id="inside-text">
                  <% if @progress < 1 %>
                    <p><%= @progress * 100 %>% funded!</p>
                  <% else %>
                    <p> Free ticket! </p>
                  <% end %>
                  <p>Current ticket price: $<%= @current_price %></p>
                  <p><a href="#" class="info-link">What does this mean?</a></p>
                </div>
              </div>
            </div>
          <!-- end of chart code -->
      </div>
      <div class="header-info">
          <h1 class="marker">WDI Conf</h1>
          <h2 class="feature">Melbourne</h2>
          <p>May 27th, 2016 | General Assembly</p>
          <p>The first fully sponsor funded conference!</p>
          <form action= "/sponsors" method="get" style="display:inline">
            <button class='btn'>Sponsor</button>
          </form>
          <form action= "/tickets" method="get" style="display:inline">
            <button class='btn'>Buy Tickets</button>
          </form>
      </div>
      <div class="ticket-info-sml">
        <% if @progress < 1 %>
          <p><%= @progress * 100 %>% funded!</p>
        <% else %>
          <p> Free ticket! </p>
        <% end %>
        <p>Current ticket price: $<%= @current_price %></p>
        <p><a href="#" class="info-link">What does this mean?</a></p>
      </div>
  </div>
</div>

<div id="overlay">
  <div id="modal">
    <h4>What's this all about?</h4>
    <p>
      WDI Conf is a world first conference, built to bridge the gap between attendees and sponsors in directly influencing the ticket price. Our conference attendees get to attend a world class conference, potentially for free due to the generosity of organizations within the industry.
    </p>
    <h4>How it works for attendees</h4>
    <p>
      We've put together an awesome conference, and the full ticket price reflects the value of the speakers and allows us to run a valuable event for our attendees. The sponsorship directly influences the final price of the tickets, and we feel this will help get people from all sorts of backgrounds to attend and get involved in tech.
    </p>
    <h4>How it works for sponsors</h4>
    <p>
      We realize how important sponsors are in putting together a conference, and want to create a strong bond and recognition between attendee and sponsor by impacting the attendee's wallet!<br>
      To make it easier to sponsor, we are trialling an automated process for companies to donate a little or a lot.<br>
      Conferences like this also go a long way to contributing to the ongoing development of people within the industry.
    </p>
  </div>
</div>
<script>
    var colors = {
  	"gray": "font-weight: bold; color: #1B2B34;",
  	"red": "font-weight: bold; color: #EC5f67;",
  	"orange": "font-weight: bold; color: #F99157;",
  	"yellow": "font-weight: bold; color: #FAC863;",
  	"green": "font-weight: bold; color: #99C794;",
  	"teal": "font-weight: bold; color: #5FB3B3;",
  	"blue": "font-weight: bold; color: #6699CC;",
  	"purple": "font-weight: bold; color: #C594C5;",
  	"brown": "font-weight: bold; color: #AB7967;"
  }

  console.log('%cMade with Love by The Splice Girls', colors.red);
  console.log('%cChristie', colors.orange);
  console.log('%cIsha', colors.yellow);
  console.log('%cLJ', colors.teal);
  console.log('%cKarina', colors.blue);
  console.log('%cPranati', colors.purple);
  console.log('%cThank you DT! And feel better soon!', colors.brown);

</script>

app/views/tickets/_info.html.erb
<div class="conference-info">
<div class="container">
<hr id="four" data-symbol="WDI Conf Details">
   <!-- grid container -->
  <div class="row" id="info-div"> <!-- row container -->
    <div class="one-half column">
      <h3>Our Lovely Location</h3>
      WDI Conf will be held in the world class facilities at General Assembly. A stones throw away from the banks of the Yarra river you'll be in the heart of Melbourne.</br></br>
      <h5>Want to chat?</h5>
      We would love to hear from you and talk through any questions you have about WDI conf.</br></br>
      <h5>Sign up to our newsletter</h5>
      All of the best WDI Conf info straight to your inbox!
      <input type="text" name="name" value="">
      <button class="btn">Sign up</button>
    </div>

    <div class="one-half column map-container">
      <div id="map">
      </div>
    </div>
  </div> <!-- close of row container -->
</div>
<!-- close of grid container -->

</div>
<a href="#" class="scrollToTop"></a>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCY0K5l9hQeeAb90ir6ogbTbmxMyLIR6ks&callback=initMap"></script>

app/views/tickets/_speakers.html.erb
<div class="speakers-container">
  <div class="container">

  <hr id="four" data-symbol="SPEAKERS">

  <% @speakers.each do |speaker| %>

    <% if speaker.id % 2 == 0 %>
        <div class="seven columns">
          <div class="one-third column">
          <img class="border headshot u-max-full-width" src="<%= image_path(speaker.image_url) %>">
          <h4><%= speaker.name %></h4>
          </div>
          <div class="two-thirds column">
          <p class="description"><%= speaker.description %></p>
          <p class="talk"><%= speaker.talk %></p>
          </div>
        </div>

    <% else %>

        <div class="seven columns offset-by-five">
            <div class="one-third column">
            <img class="border headshot u-max-full-width" src="<%= image_path(speaker.image_url) %>">
            <h4><%= speaker.name %></h4>
            </div>
            <div class="two-thirds column">
            <p class="description"><%= speaker.description %></p>
            <p class="talk"><%= speaker.talk %></p>
           </div>
        </div>

      <% end %>
    <% end %>
  </div>

</div>

app/views/tickets/_sponsors.html.erb
<div class ="sponsors-container">
  <div class="sponsors container">
    <div class="row">
      <p>With thanks to</p>
      <p>our generous sponsors...</p>  
    
    <div class="top-sponsor"> 
      <a href="<%= @sponsors[0].website %>"><img src="<%= sponsors_logo_url(url: @sponsors[0].image_url, size: 'large') %>"></a>
    </div>

    <div class="second-row-sponsors">
      <% @sponsors[1..3].each do |sponsor| %>
         <a href="<%= sponsor.website %>"><img src="<%=  sponsors_logo_url(url: sponsor.image_url, size: 'medium') %>" alt="<%= sponsor.company_name %>"></a>
      <% end %>
    </div>

  <div class ="other-sponsors">
    <% @sponsors[4..@sponsors.length].each do |sponsor| %>
      <a href="<%= sponsor.website %>"><img src="<%=  sponsors_logo_url(url: sponsor.image_url, size: 'small') %>" alt="<%= sponsor.company_name %>"></a>
    <% end %>
  </div>
  </div>
</div>

app/views/tickets/_timetable.html.erb
<div class="timetable-container">

<div class="container">
  <hr id="four" data-symbol="TIME TABLE">
  <div class="row">

    <div class="one-half column">

      <table id="timetable">
        <thead>
          <tr>
            <th>Time</th>
            <th>What</th>
            <th>Where</th>
          </tr>
          <tr id="event1" class="event">
            <td>9AM</td>
            <td >Keynote: contributing to open source as a junior</td>
            <td>Main Event Space</td>
          </tr>
          <tr id="event2" class="event">
            <td >10AM</td>
            <td>You code like a girl. Good for you!</td>
            <td>Main Event Space</td>
          </tr>
          <tr id="event3" class="event">
            <td>11AM</td>
            <td>Learning to Code - The Non-Code Skills I've Learned Along the Way</td>
            <td>Main Event Space</td>
          </tr>
          <tr id="event4" class="event">
            <td>2PM</td>
            <td>Awesome Data Visualisation</td>
            <td>Main Event Space</td>
          </tr>
          <tr id="event5" class="event">
            <td>3PM</td>
            <td>Selling Success is the Path to Success</td>
            <td>Main Event Space</td>
          </tr>

        </thead>
      </table>
    </div>

    <div class="one-half column">

      <div id="event-description">

      </div>

    </div>

  </div>
  <!-- end of row div -->
</div>
<!-- end of container div -->
</div>
<!-- end of timetable wrapper div -->

app/views/tickets/index.html.erb
<%= render partial: "hero" %>
<%= render partial: "sponsors" %>
<div id="background-gradient">
<%= render partial: "speakers" %>
<%= render partial: "events" %>
<%= render partial: "timetable" %>
</div>
<%= render partial: "info" %>
</div>

<script type="text/javascript">


</script>

app/views/tickets/soldout.html.erb
<h2> Thanks for your Interest.</h2>
<h3>But we are currently sold out.</h3>

app/views/tickets/team.html.erb
<div class="container">
  <h2 id="sponsor-header">The Splice Girl(s)</h2>
    <div class="row">
      <div class="one-third column value">
        <h2 class="value-multiplier"><img src="LJ.png"></h2>
        <h5 class="value-heading">Karina</h5>
        <p class="value-description">Passionate and pole and programming.</p>
      </div>
      <div class="one-third column value">
        <h2 class="value-multiplier">2</h2>
        <h5 class="value-heading">Isha</h5>
        <p class="value-description">Build strong brand relationships with attendees.</p>
      </div>
      <div class="one-third column value">
        <h2 class="value-multiplier">3</h2>
        <h5 class="value-heading">Pranati</h5>
        <p class="value-description">Have your brand recognised for their contributions.</p>
      </div>
    </div>
    <div class="row">
      <div class="six columns value">
        <h2 class="value-multiplier">4</h2>
        <h5 class="value-heading">Christie</h5>
        <p class="value-description">Passionate and pole and programming.</p>
      </div>
      <div class="six columns value">
        <h2 class="value-multiplier">5</h2>
        <h5 class="value-heading">LJ</h5>
        <p class="value-description">Build strong brand relationships with attendees.</p>
      </div>
    </div>
  </div>

app/views/tickets/tickets.html.erb
<div class="container">
  <h1 id="sponsor-header">WDI Conf Ticket Purchase</h1>
  <div class="tickets-container">
    <form action="/tickets/submit" method="post" id="payment-form">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <section class="accountInformation">
        <h4>Ticket Holder Details</h4>
        <ul>
          <li>
            <div class="col-span-50">
              <input type="text" id="acctFirstName" name="firstname" minlength="2" placeholder="First Name" />
            </div>
            <div class="col-span-50">
              <input type="text" id="acctLastName" name="lastname" value="" minlength="2" placeholder="Last Name" />
            </div>
          </li>
          <li>
            <div class="col-span-50">
              <input type="text" id="acctEmail" name="email" value="" placeholder="Email" />
            </div>
            <div class="col-span-50">
              <label for="">Number of Tickets</label>
              <select class="thickGrayDblBorder" id='num_of_tickets' name="num_of_tickets"></select>
            </div>
          </li>
        </ul>
      </section>
      <span class="payment-errors"></span>
      <section class="paymentInformation">
        <h3>Payment Information</h3>
        <ul>
          <li>
            <div class="col-span-100">
              <input type="text" data-stripe="number" id="cardNumber" size="20" name="cardNumber" placeholder="Credit Card #" />
            </div>
          </li>
          <li>
            <div class="col-span-50">
              <input type="text" data-stripe="exp_month" id="expMonth" size="2" name="expMonth" placeholder="Expiration Month (MM)" />
            </div>
            <div class="col-span-50">
              <input type="text" data-stripe="exp_year" id="expMonth" size="2" name="expMonth" placeholder="Expiration Year (YY)" />
            </div>
          </li>
          <li>
            <div class="col-span-50">
              <input type="text" size="4" data-stripe="cvc" id="securityCode" name="securityCode" placeholder="CVC Security Code" />
            </div>
            <div class="col-span-50">
              <div class="smallPrint whatIsThis">
              <img src="http://s.cdpn.io/6209/cc_Icon.png" /></div>
            </div>
          </li>
          <li>
            <div class="col-span-100">
            <input type="submit" class="btn" value="Submit Payment">
            </div>
          </li>
          <p class="smallPrint col-span-100">
            Charge my credit card for the full ticket price of $200. On the 26th May the final price (only equal to or less than $200) will be confirmed, and you will be refunded the difference.
          </p>
          </ul>
      </section>
    </form>
  </div>
</div>
<!-- modal -->
<div id="processing-notice" class="modal">
  <div class="modal-content">
    <p>Please wait while we are processing your payment ...</p>
  </div>
</div>

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
$(function(){
  var $select = $(".1-10");
    for (i=1;i<=10;i++){
    $('#num_of_tickets').append($('<option></option>').val(i).html(i));
    console.log('jhkn');
  }
});
$("#num_of_tickets").change(function(){
  $('#amount').html($(this).val()*200);
});
Stripe.setPublishableKey('pk_test_r8NTA6dpseAgBXLp56mMQgGA');
</script>